# fly.toml app configuration file generated for chester on 2024-04-25T17:27:29+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'chester'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 7878
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
